export const errorCodes = {
  NO_VIDEO_FOUND: "NO_VIDEO_FOUND",
  CAPTURE_NOT_SUPPORTED: "CAPTURE_NOT_SUPPORTED",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_EXPIRED: "ROOM_EXPIRED",
  ROOM_PASSWORD_REQUIRED: "ROOM_PASSWORD_REQUIRED",
  ROOM_PASSWORD_INVALID: "ROOM_PASSWORD_INVALID",
  NEGOTIATION_FAILED: "NEGOTIATION_FAILED",
  DIRECT_CONNECTIVITY_FAILED: "DIRECT_CONNECTIVITY_FAILED",
} as const;
